trigger:
- develop

pr:
  branches:
    include:
    - develop

variables:
  - name: 'pipeline_name'
    value: 'User Service (develop)'
  - name: 'service_name'
    value: 'user'

name: $[variables.pipeline_name]

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'build docker image'
  inputs:
    containerRegistry: 'Docker Hub [ujinjinjin]'
    repository: 'ujinjinjin/$(service_name)'
    command: 'build'
    Dockerfile: '$(service_name)/Dockerfile'

- task: Docker@2
  displayName: 'publish docker image'
  inputs:
    containerRegistry: 'Docker Hub [ujinjinjin]'
    repository: 'ujinjinjin/$(service_name)'
    command: 'push'