trigger:
  batch: true
  branches:
    include:
    - develop
    exclude:
    - main
  paths:
    include:
    - pipelines/user/*
    - user/*

pr:
  branches:
    include:
    - develop

variables:
  - name: 'pipeline_name'
    value: 'User Service'
  - name: 'service_name'
    value: 'user'
  - name: 'major'
    value: 0
  - name: 'minor'
    value: 0
  - name: 'patch'
    value: $[counter('user_service', 1)]
  - name: 'image_version'
    value: 'v$(major).$(minor).$(patch)-dev'

name: '$(pipeline_name) - $(Date:yyyyMMdd)$(Rev:.r)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'build docker image'
  inputs:
    containerRegistry: 'Docker Hub [ujinjinjin]'
    repository: 'ujinjinjin/$(service_name)'
    command: 'build'
    tags: '$(image_version)'
    Dockerfile: '$(service_name)/Dockerfile'

- task: Docker@2
  displayName: 'publish docker image'
  inputs:
    containerRegistry: 'Docker Hub [ujinjinjin]'
    repository: 'ujinjinjin/$(service_name)'
    command: 'push'
    tags: '$(image_version)'