trigger:
  batch: true
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - pipelines/user/*
    - user/*

pr:
  branches:
    include:
    - main
    - develop

variables:
- template: variables.yml

name: '${{ variables.pipeline_name }} - ${{ variables.image_version }}${{ variables.version_suffix }}'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'build docker image'
  inputs:
    containerRegistry: 'Docker Hub [ujinjinjin]'
    repository: 'ujinjinjin/${{ variables.service_name }}'
    command: 'build'
    tags: '${{ variables.image_version }}${{ variables.version_suffix }}'
    Dockerfile: '${{ variables.service_name }}/Dockerfile'

- task: Docker@2
  displayName: 'publish docker image'
  inputs:
    containerRegistry: 'Docker Hub [ujinjinjin]'
    repository: 'ujinjinjin/${{ variables.service_name }}'
    command: 'push'
    tags: '${{ variables.image_version }}${{ variables.version_suffix }}'
